# this will stop all jobs
jenkins_status: "stable" # "maintenance"

# refers to jenkins credential id -> will change this to vault
credential:
    git: "gitauth"
    docker: "JFrogAuth"
    sonarqube: ""
